version: "3.8"
services:
    clinic-service:
        build: .
        container_name: clinic-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: ${MYSQLUSER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQLPASSWORD}
