version: "3.8"

services:
    db:
        image: mysql:latest
        container_name: db
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: ${MYSQLDATABASE:-clinic_db}
        restart: always
        networks:
            - clinic-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    clinic-service:
        build: .
        container_name: clinic-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQLDATABASE:-clinic_db}?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: ${MYSQLPASSWORD}
        depends_on:
            - db
        restart: on-failure:2
        networks:
            - clinic-network
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

networks:
    clinic-network:
        driver: bridge
