version: "3.8"

services:
    db:
        image: mysql:8.0.42
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: clinic
        restart: always

    # clinic-service:
    #     build: .
    #     container_name: clinic-service
    #     ports:
    #         - "8080:8080"
    #     environment:
    #         SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clinic?createDatabaseIfNotExist=true
    #         SPRING_DATASOURCE_USERNAME: root
    #         SPRING_DATASOURCE_PASSWORD: test
    #     depends_on:
    #         - db
    #     restart: on-failure:2
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "0.5"
