version: "3.8"
services:
    clinic-service:
        build: .
        container_name: clinic-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://root:xANMbVbBSIJyJILUWzdlVeKRRimxYjol@yamabiko.proxy.rlwy.net:16022/railway?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: xANMbVbBSIJyJILUWzdlVeKRRimxYjol
