version: "3.8"

services:
    clinic-service:
        build: .
        container_name: clinic-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://clinic-rds.cf24ae0s8m8a.eu-north-1.rds.amazonaws.com:3306/clinic?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: adminadmin1
        restart: on-failure:2
        deploy:
            resources:
                limits:
                    cpus: "1"
