version: "3.8"
services:
    clinic-service:
        build: .
        container_name: clinic-service
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:${MySQL.MYSQL_URL}?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: ${ MySQL.MYSQLUSER }
            SPRING_DATASOURCE_PASSWORD: ${ MySQL.MYSQLPASSWORD }
