version: "3.8"

services:
  clinic-service:
    build: .
    container_name: clinic-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clinic?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 

  db:
    image: mysql:8.0 
    container_name: mysql-db
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: clinic 
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
